version: "3.8"

services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ="America/New_York"
    ports:
      - "1880:1880"
    restart: unless-stopped
    networks:
      - node-red-net
    volumes:
      - node-red-data:/data

volumes:
  node-red-data:

networks:
  node-red-net:
