version: "2.0"

services:
  dumpvdl2:
    image: ghcr.io/sdr-enthusiasts/docker-dumpvdl2:latest
    container_name: dumpvdl2
    restart: unless-stopped
    device_cgroup_rules:
      - 'c 189:* rwm'
    environment:
      - TZ="America/New_York"
      - SERIAL=00001090
      - FEED_ID=VDLM
      - FREQUENCIES=136650000;136975000;136700000;136800000
      - SERVER=acars_router
    tmpfs:
      - /run:exec,size=64M
      - /var/log
    volumes:
      - /dev:/dev:ro

    
